defaults: &defaults
  :app_name:            Tweeple Fight! Go!
  :logging:             false

  :session_secret:      nowisthetimeforallgoodmentocometotheaidoftheirbieber

  :google_api_key:      

production:
  <<: *defaults
  
development:
  <<: *defaults
  :logging:             true
  
staging:
  <<: *defaults  
  :logging:             true
